import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Canvas } from '@react-three/fiber'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter Globe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Canvas>

      </Canvas>

    </div>
  )
}
